name = "DataFrameIntervals"
uuid = "33b79e07-adbe-4034-b8be-6bacde625d75"
authors = ["David F Little <david.frank.little@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "1.6"
DataFrames = "1"
Intervals = "1.7"